//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectManagementEntities : DbContext
    {
        public ProjectManagementEntities()
            : base("name=ProjectManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BinhLuan> BinhLuans { get; set; }
        public virtual DbSet<DanhGiaDeTai> DanhGiaDeTais { get; set; }
        public virtual DbSet<DeTai> DeTais { get; set; }
        public virtual DbSet<DotKhoaLuan> DotKhoaLuans { get; set; }
        public virtual DbSet<GiangVien> GiangViens { get; set; }
        public virtual DbSet<GiangVienThuocKhoa> GiangVienThuocKhoas { get; set; }
        public virtual DbSet<KhoaHoc> KhoaHocs { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<LoaiTaiKhoan> LoaiTaiKhoans { get; set; }
        public virtual DbSet<NamHoc> NamHocs { get; set; }
        public virtual DbSet<Nganh> Nganhs { get; set; }
        public virtual DbSet<NhomSV> NhomSVs { get; set; }
        public virtual DbSet<PhanDeTaiChoDotKhoaLuan> PhanDeTaiChoDotKhoaLuans { get; set; }
        public virtual DbSet<PhanDeTaiChoGiangVien> PhanDeTaiChoGiangViens { get; set; }
        public virtual DbSet<PhanDeTaiChoNhomSV> PhanDeTaiChoNhomSVs { get; set; }
        public virtual DbSet<QuanLyLich> QuanLyLiches { get; set; }
        public virtual DbSet<SinhVienKhoaHoc> SinhVienKhoaHocs { get; set; }
        public virtual DbSet<SinhVienNganhHoc> SinhVienNganhHocs { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
        public virtual DbSet<SinhVienThuocKhoa> SinhVienThuocKhoas { get; set; }
        public virtual DbSet<SinhVienThuocNhomSV> SinhVienThuocNhomSVs { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TaiLieu> TaiLieux { get; set; }
        public virtual DbSet<TinTucThongBao> TinTucThongBaos { get; set; }
    }
}
