//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DeTai
    {
        public DeTai()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.DanhGiaDeTais = new HashSet<DanhGiaDeTai>();
            this.TaiLieux = new HashSet<TaiLieu>();
            this.PhanDeTaiChoDotKhoaLuans = new HashSet<PhanDeTaiChoDotKhoaLuan>();
            this.PhanDeTaiChoGiangViens = new HashSet<PhanDeTaiChoGiangVien>();
            this.PhanDeTaiChoNhomSVs = new HashSet<PhanDeTaiChoNhomSV>();
        }
        [Required(ErrorMessage = "Field can't be empty")]
        public decimal DeTaiId { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        [StringLength(100, ErrorMessage = "Maximum is 100")]
        public string TenDeTai { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        [StringLength(255, ErrorMessage = "Maximum is 255")]
        public string MoTa { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "SLTV must be numeric")]
        public Nullable<int> SoLuongThanhVien { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        public Nullable<System.DateTime> NgayTao { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        public Nullable<System.DateTime> NgayDangKy { get; set; }
    
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        public virtual ICollection<DanhGiaDeTai> DanhGiaDeTais { get; set; }
        public virtual ICollection<TaiLieu> TaiLieux { get; set; }
        public virtual ICollection<PhanDeTaiChoDotKhoaLuan> PhanDeTaiChoDotKhoaLuans { get; set; }
        public virtual ICollection<PhanDeTaiChoGiangVien> PhanDeTaiChoGiangViens { get; set; }
        public virtual ICollection<PhanDeTaiChoNhomSV> PhanDeTaiChoNhomSVs { get; set; }
    }
}
