//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DotKhoaLuan
    {
        public DotKhoaLuan()
        {
            this.PhanDeTaiChoDotKhoaLuans = new HashSet<PhanDeTaiChoDotKhoaLuan>();
            this.PhanSinhVienChoDotKhoaLuans = new HashSet<PhanSinhVienChoDotKhoaLuan>();
            this.QuanLyLiches = new HashSet<QuanLyLich>();
        }
    
        public decimal DotKhoaLuanId { get; set; }
        public string TenDotKhoaLuan { get; set; }
        public decimal NamHocHocKyId { get; set; }
    
        public virtual NamHoc NamHoc { get; set; }
        public virtual ICollection<PhanDeTaiChoDotKhoaLuan> PhanDeTaiChoDotKhoaLuans { get; set; }
        public virtual ICollection<PhanSinhVienChoDotKhoaLuan> PhanSinhVienChoDotKhoaLuans { get; set; }
        public virtual ICollection<QuanLyLich> QuanLyLiches { get; set; }
    }
}
