//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GiangVien
    {
        public GiangVien()
        {
            this.GiangVienThuocKhoas = new HashSet<GiangVienThuocKhoa>();
            this.PhanDeTaiChoGiangViens = new HashSet<PhanDeTaiChoGiangVien>();
            this.TaiKhoans = new HashSet<TaiKhoan>();
        }
        [Required(ErrorMessage = "Field can't be empty")]
        public string GiangVienId { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        public bool GioiTinh { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        [StringLength(200, ErrorMessage = "Maximum is 200")]
        public string HoTen { get; set; }
    
        public virtual ICollection<GiangVienThuocKhoa> GiangVienThuocKhoas { get; set; }
        public virtual ICollection<PhanDeTaiChoGiangVien> PhanDeTaiChoGiangViens { get; set; }
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
    }
}
