//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Khoa
    {
        public Khoa()
        {
            this.GiangVienThuocKhoas = new HashSet<GiangVienThuocKhoa>();
            this.Nganhs = new HashSet<Nganh>();
            this.NhomSVs = new HashSet<NhomSV>();
            this.SinhVienThuocKhoas = new HashSet<SinhVienThuocKhoa>();
            this.TinTucThongBaos = new HashSet<TinTucThongBao>();
        }
        [Required(ErrorMessage = "Field can't be empty")]
        public decimal KhoaId { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        [StringLength(100, ErrorMessage = "Maximum is 100")]
        public string TenKhoa { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        [StringLength(100, ErrorMessage = "Maximum is 100")]
        public string DiaChi { get; set; }
    
        public virtual ICollection<GiangVienThuocKhoa> GiangVienThuocKhoas { get; set; }
        public virtual ICollection<Nganh> Nganhs { get; set; }
        public virtual ICollection<NhomSV> NhomSVs { get; set; }
        public virtual ICollection<SinhVienThuocKhoa> SinhVienThuocKhoas { get; set; }
        public virtual ICollection<TinTucThongBao> TinTucThongBaos { get; set; }
    }
}
