//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiTaiKhoan
    {
        public LoaiTaiKhoan()
        {
            this.TaiKhoans = new HashSet<TaiKhoan>();
        }
    
        public decimal LoaiTaiKhoanId { get; set; }
        public string TenLoaiTaiKhoan { get; set; }
    
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
    }
}
