//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nganh
    {
        public Nganh()
        {
            this.SinhVienKhoaHocs = new HashSet<SinhVienKhoaHoc>();
        }
    
        public decimal NganhId { get; set; }
        public string TenNganh { get; set; }
        public Nullable<decimal> KhoaId { get; set; }
    
        public virtual Khoa Khoa { get; set; }
        public virtual ICollection<SinhVienKhoaHoc> SinhVienKhoaHocs { get; set; }
    }
}
