//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NhomSV
    {
        public NhomSV()
        {
            this.PhanDeTaiChoNhomSVs = new HashSet<PhanDeTaiChoNhomSV>();
            this.SinhVienThuocNhomSVs = new HashSet<SinhVienThuocNhomSV>();
        }
        [Required(ErrorMessage = "Field can't be empty")]
        public decimal NhomSVId { get; set; }

        [Required(ErrorMessage = "Field can't be empty")]
        [StringLength(100, ErrorMessage = "Maximum is 100")]
        public string TenNhom { get; set; }

        [Required(ErrorMessage = "Field can't be empty")]
        public Nullable<decimal> KhoaId { get; set; }
    
        public virtual Khoa Khoa { get; set; }
        public virtual ICollection<PhanDeTaiChoNhomSV> PhanDeTaiChoNhomSVs { get; set; }
        public virtual ICollection<SinhVienThuocNhomSV> SinhVienThuocNhomSVs { get; set; }
    }
}
