//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanDeTaiChoNhomSV
    {
        public decimal NhomSVId { get; set; }
        public decimal DeTaiId { get; set; }
        public Nullable<System.DateTime> NgayPhanDeTai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DeTai DeTai { get; set; }
        public virtual NhomSV NhomSV { get; set; }
    }
}
