//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PhanDeTaiChoNhomSV
    {

        [Required(ErrorMessage = "Field can't be empty")]
        public decimal NhomSVId { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        public decimal DeTaiId { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        public Nullable<System.DateTime> NgayPhanDeTai { get; set; }
        [StringLength(200, ErrorMessage = "Maximum is 200")]
        public string GhiChu { get; set; }
    
        public virtual DeTai DeTai { get; set; }
        public virtual NhomSV NhomSV { get; set; }
    }
}
