//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SinhVienThuocNhomSV
    {

        [Required(ErrorMessage = "Field can't be empty")]
        public decimal NhomSVId { get; set; }

        [Required(ErrorMessage = "Field can't be empty")]
        public string SinhVienId { get; set; }

        [Required(ErrorMessage = "Field can't be empty")]
        public Nullable<System.DateTime> NgayPhan { get; set; }
    
        public virtual NhomSV NhomSV { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
