//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public TaiKhoan()
        {
            this.TinTucThongBaos = new HashSet<TinTucThongBao>();
        }
    
        public decimal TaiKhoanId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> SDT { get; set; }
        public Nullable<decimal> SDTK { get; set; }
        public Nullable<decimal> LoaiTaiKhoanId { get; set; }
        public string SinhVienId { get; set; }
        public string GiangVienId { get; set; }
        public Nullable<bool> LaQuanTri { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual LoaiTaiKhoan LoaiTaiKhoan { get; set; }
        public virtual ICollection<TinTucThongBao> TinTucThongBaos { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
