//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiLieu
    {
        [Required(ErrorMessage = "Field can't be empty")]
        public decimal TaiLieuId { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        [StringLength(100, ErrorMessage = "Maximum is 100")]
        public string TenTaiLieu { get; set; }

        public string TepTinDinhKem { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        public Nullable<decimal> DeTaiId { get; set; }
    
        public virtual DeTai DeTai { get; set; }
    }
}
