//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrangThai
    {
        public TrangThai()
        {
            this.SinhViens = new HashSet<SinhVien>();
        }
    
        public decimal TrangThaiId { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<SinhVien> SinhViens { get; set; }
    }
}
